name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup:
    runs-on: ubuntu-latest
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - run: make
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - run: make test
    
